[project]
name = "tictactoe"
version = "0.1.0"
description = "Tic-Tac-Toe, Connect Four and variants"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.15.0",
    "ruff>=0.9.7",
]
